name: bisan_systems_erp
description: Bisan Systems ERP
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.5
  dwds: ^16.0.1
  dio: ^4.0.6
  flutter_toolbar: ^0.0.2
  horizontal_data_table: ^4.1.3
  rxdart: ^0.27.7
  reflectable: ^4.0.4
  advanced_datatable: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
